column_mapping = {
    "mun_name": "mun_name",
    "minint_fin": "minint_fin",
    "prov_name": "prov_name",
    "prov_istat": "prov_istat",
    "prov_ist_1": "prov_ist_1",
    "prov_acr": "prov_acr",
    "reg_name": "reg_name",
    "reg_istat_": "reg_istat_",
    "reg_ista_1": "reg_ista_1",
    "opdm_id": "opdm_id",
    "com_catast": "com_catast",
    "com_istat_": "com_istat_",
    "com_ista_1": "com_ista_1",
    "area": "area",
    "geometry": "geometry",
    "cattle_under_one_year_old_ktn": "cattle under one year old (ktn)",
    "cattle_under_one_year_old_males_ktn": "cattle under one year old: males (ktn)",
    "cattle_under_one_year_old_females_ktn": "cattle under one year old: females (ktn)",
    "cattle_from_one_year_to_less_than_two_years_old_males_ktn": "Cattle from one year to less than two years old: males (ktn)",
    "cattle_from_one_year_to_less_than_two_years_old_females_ktn": "Cattle from one year to less than two years old: females (ktn)",
    "cattle_two_years_old_and_older_ktn": "cattle two years old and older (ktn)",
    "cattle_two_years_and_older_males_ktn": "Cattle two years and older: males (ktn)",
    "cattle_two_years_and_older_females_ktn": "Cattle two years and older: females (ktn)",
    "cattle_two_years_and_older_breeding_heifers_ktn": "Cattle two years and older: breeding heifers (ktn)",
    "cattle_two_years_and_older_heifers_for_slaughter_ktn": "Cattle two years and older: heifers for slaughter (ktn)",
    "cattle_two_years_and_older_dairy_cows_ktn": "Cattle two years and older: dairy cows (ktn)",
    "cattle_aged_2_years_and_over_other_cows_beef_andor_working_ktn": "Cattle aged 2 years and over: other cows (beef and/or working) (ktn)",
    "sheep_ktn": "sheep (ktn)",
    "dairy_sheep_ktn": "dairy sheep (ktn)",
    "non_dairy_sheep_ktn": "non dairy sheep (ktn)",
    "other_sheep_ktn": "other sheep (ktn)",
    "total_buffaloes_ktn": "total buffaloes (ktn)",
    "buffalo_calves_ktn": "buffalo calves (ktn)",
    "bufalloes_ktn": "bufalloes (ktn)",
    "other_buffaloes_ktn": "other buffaloes (ktn)",
    "goats_ktn": "goats (ktn)",
    "other_goats_ktn": "other goats (ktn)",
    "chickens_for_meat_ktn": "chickens for meat (ktn)",
    "egglaying_hens_ktn": "egg-laying hens (ktn)",
    "turkeys_ktn": "turkeys (ktn)",
    "pharaoh_ktn": "pharaoh (ktn)",
    "geese_ktn": "geese (ktn)",
    "other_poultry_ktn": "other poultry (ktn)",
    "ostriches_ktn": "ostriches (ktn)",
    "pigs_weighing_less_than_20_kg_ktn": "pigs weighing less than 20 kg (ktn)",
    "pigs_from_20_kg_to_less_than_50_kg_ktn": "pigs from 20 kg to less than 50 kg (ktn)",
    "fattening_pigs_of_50_kg_and_more_ktn": "fattening pigs of 50 kg and more (ktn)",
    "fattening_pigs_from_50_kg_to_less_than_80_kg_ktn": "fattening pigs from 50 kg to less than 80 kg (ktn)",
    "fattening_pigs_from_80_kg_to_less_than_110_kg_ktn": "fattening pigs from 80 kg to less than 110 kg (ktn)",
    "fattening_pigs_of_110_kg_and_more_ktn": "fattening pigs of 110 kg and more (ktn)",
    "breeding_pigs_of_50_kg_and_more_ktn": "breeding pigs of 50 kg and more (ktn)",
    "breeding_pigs_of_50_kg_and_more_boars_ktn": "breeding pigs of 50 kg and more: boars (ktn)",
    "breeding_pigs_of_50_kg_and_more_mounted_sows_ktn": "breeding pigs of 50 kg and more: mounted sows (ktn)",
    "breeding_pigs_of_50_kg_and_more_other_sows_ktn": "breeding pigs of 50 kg and more: other sows (ktn)",
    "cattle_under_one_year_old_no_heads": "cattle under one year old_(no. heads)",
    "cattle_under_one_year_old_males_no_heads": "cattle under one year old: males_(no. heads)",
    "cattle_under_one_year_old_females_no_heads": "cattle under one year old: females_(no. heads)",
    "cattle_from_one_year_to_less_than_two_years_old_males_no_heads": "Cattle from one year to less than two years old: males_(no. heads)",
    "cattle_from_one_year_to_less_than_two_years_old_females_no_heads": "Cattle from one year to less than two years old: females_(no. heads)",
    "cattle_two_years_old_and_older_no_heads": "cattle two years old and older_(no. heads)",
    "cattle_two_years_and_older_males_no_heads": "Cattle two years and older: males_(no. heads)",
    "cattle_two_years_and_older_females_no_heads": "Cattle two years and older: females_(no. heads)",
    "cattle_two_years_and_older_breeding_heifers_no_heads": "Cattle two years and older: breeding heifers_(no. heads)",
    "cattle_two_years_and_older_heifers_for_slaughter_no_heads": "Cattle two years and older: heifers for slaughter_(no. heads)",
    "cattle_two_years_and_older_dairy_cows_no_heads": "Cattle two years and older: dairy cows_(no. heads)",
    "cattle_aged_2_years_and_over_other_cows_beef_andor_working_no_h": "Cattle aged 2 years and over: other cows (beef and/or working)_(no. heads)",
    "sheep_no_heads": "sheep_(no. heads)",
    "dairy_sheep_no_heads": "dairy sheep_(no. heads)",
    "non_dairy_sheep_no_heads": "non dairy sheep_(no. heads)",
    "other_sheep_no_heads": "other sheep_(no. heads)",
    "total_buffaloes_no_heads": "total buffaloes_(no. heads)",
    "buffalo_calves_no_heads": "buffalo calves_(no. heads)",
    "bufalloes_no_heads": "bufalloes_(no. heads)",
    "other_buffaloes_no_heads": "other buffaloes_(no. heads)",
    "goats_no_heads": "goats_(no. heads)",
    "other_goats_no_heads": "other goats_(no. heads)",
    "chickens_for_meat_no_heads": "chickens for meat_(no. heads)",
    "egglaying_hens_no_heads": "egg-laying hens_(no. heads)",
    "turkeys_no_heads": "turkeys_(no. heads)",
    "pharaoh_no_heads": "pharaoh_(no. heads)",
    "geese_no_heads": "geese_(no. heads)",
    "other_poultry_no_heads": "other poultry_(no. heads)",
    "ostriches_no_heads": "ostriches_(no. heads)",
    "pigs_weighing_less_than_20_kg_no_heads": "pigs weighing less than 20 kg_(no. heads)",
    "pigs_from_20_kg_to_less_than_50_kg_no_heads": "pigs from 20 kg to less than 50 kg_(no. heads)",
    "fattening_pigs_of_50_kg_and_more_no_heads": "fattening pigs of 50 kg and more_(no. heads)",
    "fattening_pigs_from_50_kg_to_less_than_80_kg_no_heads": "fattening pigs from 50 kg to less than 80 kg_(no. heads)",
    "fattening_pigs_from_80_kg_to_less_than_110_kg_no_heads": "fattening pigs from 80 kg to less than 110 kg_(no. heads)",
    "fattening_pigs_of_110_kg_and_more_no_heads": "fattening pigs of 110 kg and more_(no. heads)",
    "breeding_pigs_of_50_kg_and_more_no_heads": "breeding pigs of 50 kg and more_(no. heads)",
    "breeding_pigs_of_50_kg_and_more_boars_no_heads": "breeding pigs of 50 kg and more: boars_(no. heads)",
    "breeding_pigs_of_50_kg_and_more_mounted_sows_no_heads": "breeding pigs of 50 kg and more: mounted sows_(no. heads)",
    "breeding_pigs_of_50_kg_and_more_other_sows_no_heads": "breeding pigs of 50 kg and more: other sows_(no. heads)",
    "cereals_for_the_production_of_grain_ktn": "cereals for the production of grain (ktn)",
    "dried_legumes_ktn": "dried legumes (ktn)",
    "potato_ktn": "potato (ktn)",
    "sugar_beet_ktn": "sugar beet (ktn)",
    "forage_root_crops_ktn": "forage root crops (ktn)",
    "industrial_plants_ktn": "industrial plants (ktn)",
    "vegetables_ktn": "vegetables (ktn)",
    "flowers_and_ornamental_plants_ktn": "flowers and ornamental plants (ktn)",
    "seedlings_ktn": "seedlings (ktn)",
    "alternate_forage_ktn": "alternate forage (ktn)",
    "seeds_ktn": "seeds (ktn)",
    "fallow_land_ktn": "fallow land (ktn)",
    "agricultural_woody_crops_ktn": "agricultural woody crops (ktn)",
    "vinesgrapevines_ktn": "vines/grapevines (ktn)",
    "olive_trees_ktn": "olive trees (ktn)",
    "citrus_fruits_ktn": "citrus fruits (ktn)",
    "fruitbearing_ktn": "fruit-bearing (ktn)",
    "nurseries_ktn": "nurseries (ktn)",
    "other_agricultural_woody_crops_ktn": "other agricultural woody crops (ktn)",
    "agricultural_woody_crops_in_greenhouses_ktn": "agricultural woody crops in greenhouses (ktn)",
    "family_gardens_ktn": "family gardens (ktn)",
    "permanent_meadows_and_pastures_ktn": "permanent meadows and pastures (ktn)",
    "arboriculture_for_wood_attached_to_agricultural_companies_ktn": "arboriculture for wood attached to agricultural companies (ktn)",
    "woods_annexed_to_agricultural_companies_ktn": "woods annexed to agricultural companies (ktn)",
    "unused_agricultural_area_ktn": "unused agricultural area (ktn)",
    "other_surface_ktn": "other surface (ktn)",
    "mushrooms_in_caves_underground_or_in_special_buildings_ktn": "mushrooms in caves, underground or in special buildings (ktn)",
    "greenhouses_ktn": "greenhouses (ktn)",
    "energy_crops_ktn": "energy crops (ktn)",
    "Source_Date": "Source_Date",
    "ingestion_time_stamp": "ingestion_time_stamp",
}

feedstock_dict = {
    # Float columns (end with 'ktn' or '_(no. heads)')
    "cattle under one year old (ktn)": "float64",
    "cattle under one year old: males (ktn)": "float64",
    "cattle under one year old: females (ktn)": "float64",
    "Cattle from one year to less than two years old: males (ktn)": "float64",
    "Cattle from one year to less than two years old: females (ktn)": "float64",
    "cattle two years old and older (ktn)": "float64",
    "Cattle two years and older: males (ktn)": "float64",
    "Cattle two years and older: females (ktn)": "float64",
    "Cattle two years and older: breeding heifers (ktn)": "float64",
    "Cattle two years and older: heifers for slaughter (ktn)": "float64",
    "Cattle two years and older: dairy cows (ktn)": "float64",
    "Cattle aged 2 years and over: other cows (beef and/or working) (ktn)": "float64",
    "sheep (ktn)": "float64",
    "dairy sheep (ktn)": "float64",
    "non dairy sheep (ktn)": "float64",
    "other sheep (ktn)": "float64",
    "total buffaloes (ktn)": "float64",
    "buffalo calves (ktn)": "float64",
    "bufalloes (ktn)": "float64",
    "other buffaloes (ktn)": "float64",
    "goats (ktn)": "float64",
    "other goats (ktn)": "float64",
    "chickens for meat (ktn)": "float64",
    "egg-laying hens (ktn)": "float64",
    "turkeys (ktn)": "float64",
    "pharaoh (ktn)": "float64",
    "geese (ktn)": "float64",
    "other poultry (ktn)": "float64",
    "ostriches (ktn)": "float64",
    "pigs weighing less than 20 kg (ktn)": "float64",
    "pigs from 20 kg to less than 50 kg (ktn)": "float64",
    "fattening pigs of 50 kg and more (ktn)": "float64",
    "fattening pigs from 50 kg to less than 80 kg (ktn)": "float64",
    "fattening pigs from 80 kg to less than 110 kg (ktn)": "float64",
    "fattening pigs of 110 kg and more (ktn)": "float64",
    "breeding pigs of 50 kg and more (ktn)": "float64",
    "breeding pigs of 50 kg and more: boars (ktn)": "float64",
    "breeding pigs of 50 kg and more: mounted sows (ktn)": "float64",
    "breeding pigs of 50 kg and more: other sows (ktn)": "float64",
    "cattle under one year old_(no. heads)": "float64",
    "cattle under one year old: males_(no. heads)": "float64",
    "cattle under one year old: females_(no. heads)": "float64",
    "cattle from one to less than two years old_(no. heads)": "float64",
    "Cattle from one year to less than two years old: males_(no. heads)": "float64",
    "Cattle from one year to less than two years old: females_(no. heads)": "float64",
    "cattle two years old and older_(no. heads)": "float64",
    "Cattle two years and older: males_(no. heads)": "float64",
    "Cattle two years and older: females_(no. heads)": "float64",
    "Cattle two years and older: breeding heifers_(no. heads)": "float64",
    "Cattle two years and older: heifers for slaughter_(no. heads)": "float64",
    "Cattle two years and older: dairy cows_(no. heads)": "float64",
    "Cattle aged 2 years and over: other cows (beef and/or working)_(no. heads)": "float64",
    "sheep_(no. heads)": "float64",
    "dairy sheep_(no. heads)": "float64",
    "non dairy sheep_(no. heads)": "float64",
    "other sheep_(no. heads)": "float64",
    "total buffaloes_(no. heads)": "float64",
    "buffalo calves_(no. heads)": "float64",
    "bufalloes_(no. heads)": "float64",
    "other buffaloes_(no. heads)": "float64",
    "total goats_(no. heads)": "float64",
    "goats_(no. heads)": "float64",
    "other goats_(no. heads)": "float64",
    "chickens for meat_(no. heads)": "float64",
    "egg-laying hens_(no. heads)": "float64",
    "turkeys_(no. heads)": "float64",
    "pharaoh_(no. heads)": "float64",
    "geese_(no. heads)": "float64",
    "other poultry_(no. heads)": "float64",
    "ostriches_(no. heads)": "float64",
    "pigs weighing less than 20 kg_(no. heads)": "float64",
    "pigs from 20 kg to less than 50 kg_(no. heads)": "float64",
    "fattening pigs of 50 kg and more_(no. heads)": "float64",
    "fattening pigs from 50 kg to less than 80 kg_(no. heads)": "float64",
    "fattening pigs from 80 kg to less than 110 kg_(no. heads)": "float64",
    "fattening pigs of 110 kg and more_(no. heads)": "float64",
    "breeding pigs of 50 kg and more_(no. heads)": "float64",
    "breeding pigs of 50 kg and more: boars_(no. heads)": "float64",
    "breeding pigs of 50 kg and more: mounted sows_(no. heads)": "float64",
    "breeding pigs of 50 kg and more: other sows_(no. heads)": "float64",
    # Float column
    "area": "float64",
    # Geometry column
    "geometry": "geometry",
    # String columns
    "mun_name": "string",
    "minint_fin": "string",
    "prov_name": "string",
    "prov_istat": "string",
    "prov_ist_1": "string",
    "prov_acr": "string",
    "reg_name": "string",
    "reg_istat_": "string",
    "reg_ista_1": "string",
    "opdm_id": "string",
    "com_catast": "string",
    "com_istat_": "string",
    "com_ista_1": "string",
}
